language: cpp
sudo: required
dist: trusty
services:
- docker
git:
  depth: 5
notifications:
  slack:
    secure: iS767Cc5C6lnDADvTqt5aypq4XaVWvgqJsdWTV1ia6E8tGxzbf/jRtRkKQkzEFrnN7xjc/q93/Gd1kcJFwyq0vA0eeX8GhnlJx1mPxktgeguNiKzCaiBmyLiixpwy/yClHdvrmv/mnR4PbkaG4tYBod6n4BpnaQQNqL3V0ie25rF4PJtpos+QQmQzCxzEU8nXm9f54pYVfVX5v9rkz0vmltX7GceYayvcMHipBCaoYDJNQqVAGr0jt+wfw93BFHsOb+EQBCB4Gw5MRNfiDeYRjrI6SXkPeb6S0R7c7fOGnk68hDI1j9Yp1i+VRpxbKRGwEeWHXhI6A7XeUenSdDvIZp/42nubdmQcXjeCLk6NRGflWPpwk5Evy74csN12hjE+cGfQpI9/oKnufly15+8BQL+PUGtaFa8rU2UfevdK32IpMeOeY5XbH6KQ4OXLAzW5211tZZaL0BTZp2TEdTskgtSDuyq3oNDAkWxH9BQYtWbAVqRgPu1nl5oXj9IG+q2UI1QG0JuKQ9hduFlyQ8NSCXVcQOQwpzW3CDAMSUl2Pe00/djgi6sdHu3i3ur9HEnrniwskl+VElUXPJYmA82U1UVF6NFhySS64y3QRdHNXNs7iQBTywbjSRSVW6YQB4bW8JY2ykyaJEjpXtXSumEYFjLvRFhU0cZDU4lqiO7ZlA=
  irc:
  - ircs://chat.freenode.net:7070#grangerhub
  email:
    on_success: change
    on_failure: change
matrix:
  include:
  - os: linux
    env: PLATFORM=linux
    before_install:
    - docker pull grangerhub/tremulous13:latest
    - docker run -e PLATFORM -v $(pwd):/usr/src grangerhub/tremulous13:latest ./misc/docker-build.sh
    script:
    - true
  - os: linux
    env: PLATFORM=mingw32
    before_install:
    - docker pull grangerhub/tremulous13:latest
    - docker run -e PLATFORM -v $(pwd):/usr/src grangerhub/tremulous13:latest ./misc/docker-build.sh
    script:
    - true
  - os: linux
    env: PLATFORM=mingw32 ARCH=x86
    before_install:
    - docker pull grangerhub/tremulous13:latest
    - docker run -e ARCH -e PLATFORM -v $(pwd):/usr/src grangerhub/tremulous13:latest
      ./misc/docker-build.sh
    script:
    - true
  - os: osx
    osx_image: xcode8
    compiler: clang
    env: ARCH=x86_64
    before_install:
    - rm -rf build
    script:
    - "./misc/travis-ci-build.sh"
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: build/*.zip
  on:
    repo: GrangerHub/tremulous
    tags: true
